export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const SET_DONE_SUCCESS = "SET_DONE_SUCCESS";
export const SET_UNDONE_SUCCESS = "SET_UNDONE_SUCCESS";
